description: |
  The Node may represent any part of a board, the tree like structure of the board is defined by boardId and parentId as well as by type.

  Valid types are `board, list, task and entry`
properties:
  name: string
  boardId?: string
  parentId?: string
  providerID?: string
  position: integer
  type:
    type: string
    enum: [ board, list, task, entry ]
  description?: string
  creator?: User
  updater?: User
  completed?: boolean
  template?: boolean
  assignments?: object[]
  tags?: string[]
  due?: date-only
  start?: date-only
  end?: date-only
  fields?: object[]
  links?: object[]
  colorLabels?: string[]
  colors?: integer[]
  linkedBoard?: string
  parent?: NodePreview
  board?: NodePreview

