properties:
  id: string
  name: string
  image: string
  link: string
  email:
    type: string
    required: false
  provider:
    type: string
    required: false
example: !include ../examples/user.json
